# Generated by Django 3.2.18 on 2024-06-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0004_auto_20200722_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='grouped_into',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_entities.person'),
        ),
    ]
