# Generated by Django 3.2.18 on 2023-12-04 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_entities', '0004_auto_20200722_1231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600)),
                ('status', models.CharField(choices=[('unchecked', 'unchecked'), ('checked group', 'checked group'), ('checked for other groups', 'checked for other groups'), ('checked all members', 'checked all members'), ('ready to merge', 'ready to merge'), ('merged', 'merged')], default='unchecked', max_length=300)),
                ('_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('marked', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'dubletten_tool_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('single', 'Single'), ('merged', 'Merged')], default='single', max_length=300)),
                ('marked', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('_names', models.JSONField(null=True)),
                ('_first_names', models.JSONField(null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis_entities.person')),
            ],
            options={
                'db_table': 'dubletten_tool_personproxy',
                'ordering': ['person__name'],
            },
        ),
        migrations.CreateModel(
            name='StatusButtonGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('short', models.CharField(default='BT', max_length=4)),
            ],
            options={
                'db_table': 'dubletten_tool_statusbuttongrouptype',
            },
        ),
        migrations.CreateModel(
            name='StatusButtonProxyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'dubletten_tool_statusbuttonproxytype',
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dubletten_tool_suggestions',
            },
        ),
        migrations.CreateModel(
            name='StatusButtonProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_deduplication.statusbuttonproxytype')),
                ('related_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_deduplication.personproxy')),
            ],
            options={
                'db_table': 'dubletten_tool_statusbuttonproxy',
            },
        ),
        migrations.CreateModel(
            name='StatusButtonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_deduplication.statusbuttongrouptype')),
                ('related_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_deduplication.group')),
            ],
            options={
                'db_table': 'dubletten_tool_statusbuttongroup',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='viecpro_deduplication.PersonProxy'),
        ),
        migrations.AddField(
            model_name='group',
            name='vorfin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_group', to='apis_entities.person'),
        ),
        migrations.CreateModel(
            name='DublettenLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=600)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dubletten_tool_dublettenlog',
            },
        ),
    ]
