# Generated by Django 3.2.18 on 2023-12-04 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apis_vocabularies', '0002_texttype_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis_entities', '0004_auto_20200722_1231'),
        ('apis_metainfo', '0006_remove_text_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('server_directory', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, max_length=600, null=True)),
                ('year', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apis_import_project_datasource',
            },
        ),
        migrations.CreateModel(
            name='DataSourcePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.IntegerField()),
                ('page_token', models.CharField(blank=True, max_length=20, null=True)),
                ('DataSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.datasource')),
            ],
            options={
                'db_table': 'apis_import_project_datasourcepage',
            },
        ),
        migrations.CreateModel(
            name='GenericCollectionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'apis_import_project_genericcollectionentry',
            },
        ),
        migrations.CreateModel(
            name='ImportProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Describe your project here.', max_length=2000, null=True)),
                ('DataSources', models.ManyToManyField(blank=True, help_text='Consider adding existing Datasources uploaded by you to this Project. Or upload/add additional Datasources later.', to='viecpro_import.DataSource')),
                ('Editors', models.ManyToManyField(blank=True, help_text='Add users that should be able to edit this project.', related_name='Editors', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_metainfo.collection')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apis_import_project_importproject',
            },
        ),
        migrations.CreateModel(
            name='PageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.ManyToManyField(related_name='created', to='viecpro_import.GenericCollectionEntry')),
                ('edited_in', models.ManyToManyField(related_name='edited', to='viecpro_import.GenericCollectionEntry')),
            ],
            options={
                'db_table': 'apis_import_project_pagecollection',
            },
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viecpro_import.datasource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.importproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apis_import_project_projectstate',
            },
        ),
        migrations.CreateModel(
            name='ProjectCollectionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(blank=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_json', to='viecpro_import.genericcollectionentry')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.importproject')),
            ],
            options={
                'db_table': 'apis_import_project_projectcollectionentry',
            },
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.OneToOneField(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viecpro_import.pagecollection')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_vocabularies.personinstitutionrelation')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_entities.institution')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.datasourcepage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.importproject')),
            ],
            options={
                'db_table': 'apis_import_project_pagedata',
            },
        ),
        migrations.CreateModel(
            name='DataSourceProjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.datasource')),
                ('last_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viecpro_import.datasourcepage')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viecpro_import.importproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apis_import_project_datasourceprojectstate',
            },
        ),
    ]
