version: "3.8"

services:
  app:
    env_file: devcontainer.env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql

    env_file: devcontainer.env

  ts:
    image: typesense/typesense:0.24.1
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=xyz --enable-cors"
    ports:
      - "8111:8108"
    volumes:
      - typesense-data:/data

  redis:
    image: arm64v8/redis
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data

volumes:
  mariadb-data:
  redis-data:
  typesense-data:
