# Generated by Django 3.2.18 on 2024-02-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_metainfo', '0006_remove_text_lang'),
        ('apis_vocabularies', '0002_texttype_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToplevelFunction',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('subsumed_functions_set', models.ManyToManyField(related_name='toplevel_functions_set', to='apis_vocabularies.PersonInstitutionRelation')),
            ],
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='AlternativeFunctionName',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('functions_set', models.ManyToManyField(related_name='alternative_names_set', to='apis_vocabularies.PersonInstitutionRelation')),
            ],
            bases=('apis_metainfo.tempentityclass',),
        ),
    ]
